# Generated by Django 3.2.7 on 2021-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('snacks', 'snacks'), ('fast food', 'fast food'), ('food', 'food'), ('ice cream', 'ice cream'), ('juice', 'juice')], max_length=100)),
                ('product_desc', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_category', models.TextField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
