# Generated by Django 3.2.7 on 2021-10-08 04:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_cart_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 4, 6, 25, 475487, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_time', models.DateTimeField(default=datetime.datetime(2021, 10, 8, 4, 6, 25, 475487, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
