# Generated by Django 3.2.7 on 2021-10-08 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211008_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_dislikes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_likes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 4, 24, 51, 185604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 4, 24, 51, 185604, tzinfo=utc)),
        ),
    ]
