# Generated by Django 3.2.7 on 2021-10-08 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211008_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_likes',
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 5, 34, 21, 831578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 5, 34, 21, 831578, tzinfo=utc)),
        ),
    ]
