# Generated by Django 3.2.7 on 2021-10-08 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211008_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dislike',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 5, 37, 48, 205884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 5, 37, 48, 205884, tzinfo=utc)),
        ),
    ]
