# Generated by Django 3.2.7 on 2021-10-09 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20211008_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 3, 37, 39, 671584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 3, 37, 39, 671584, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(null=True)),
                ('city', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('phno', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
